src/e_psu/admin_kelola/urls.py
from django.urls import path

from . import views

app_name = "admin_kelola"
urlpatterns = [
    path("login", views.login_admin_kelola, name="login"),
    path("register", views.register_admin_kelola, name="register"),
    path("logout", views.logout_admin_kelola, name="logout"),
    path("dashboard", views.index, name="index"),
    path("perwakilan_penghuni/tambah", views.perwakilan_penghuni_tambah, name="perwakilan_penghuni_tambah"),
    path("laporan/tambah", views.laporan_tambah, name="laporan_tambah"),
    path("laporan/tampil/<int:id>", views.laporan_tampil, name="laporan_tampil"),
    path("laporan/ubah/<int:id>", views.laporan_ubah, name="laporan_ubah"),
    path("laporan/hapus/<int:id>", views.laporan_hapus, name="laporan_hapus"),
    path("serah_terima/tambah", views.serah_terima_tambah, name="serah_terima_tambah"),
    path("serah_terima/tampil/<int:id>", views.serah_terima_tampil, name="serah_terima_tampil"),
    path("serah_terima/ubah/<int:id>", views.serah_terima_ubah, name="serah_terima_ubah"),
    path("serah_terima/hapus/<int:id>", views.serah_terima_hapus, name="serah_terima_hapus"),
]

src/e_psu/e_psu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path("", home_view, name="home"),
    path('admin/', admin.site.urls),
    path('admin_kelola/serah_terima/', include("serah_terima.urls")),
    path('laporan/', include("laporan.urls")),
    path('warga/', include("warga.urls")),
    path('admin_kelola/', include("admin_kelola.urls")),
    path('admin_skpd/', include("admin_skpd.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/e_psu/serah_terima/urls.py
from django.urls import path

from . import views

app_name = "serah_terima"
urlpatterns = [
#     path("", views.index, name="index"),
#     path("cari", views.cari, name="cari"),
#     path("tambah", views.tambah, name="tambah"),
#     path("tampil/<int:id>", views.tampil, name="tampil"),
#     path("ubah/<int:id>", views.ubah, name="ubah"),
#     path("hapus/<int:id>", views.hapus, name="hapus"),
]

src/e_psu/admin_kelola/models.py
from django.db import models
from account.models import Account
from django.db.models.signals import post_save
# Create your models here.
class AdminKelola(models.Model):
    user = models.OneToOneField(Account,on_delete=models.CASCADE, primary_key = True)
    nama = models.CharField(max_length=30)

    class Meta:
        db_table= "kelola_adminkelola"
    
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            profile, created = AdminKelola.objects.get_or_create(user=instance)
    
    post_save.connect(create_user_profile, sender=Account)

src/e_psu/serah_terima/models.py
from django.db import models
from admin_kelola.models import AdminKelola
from uuid import uuid4
import os
from smartfields import fields
from django.utils.deconstruct import deconstructible

@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        filename = '{}.{}'.format(uuid4().hex, ext)
        return os.path.join(self.path, filename)

class Dokumen(models.Model):
    video = fields.FileField(upload_to=PathAndRename("serah_terima/dokumen/video/"))
    foto = fields.ImageField(upload_to=PathAndRename("serah_terima/dokumen/foto/"))
    salinan_laporan = fields.FileField(upload_to=PathAndRename("serah_terima/dokumen/salinan_laporan/"))
    admin_kelola = models.ForeignKey(AdminKelola,on_delete=models.CASCADE)
    status_pengelolaan_text = models.CharField(max_length=100, blank=True)
    pola_pengelolaan_text = models.CharField(max_length=100, blank=True)
    regulasi_pemanfaatan_psu_text = models.CharField(max_length=100,blank=True)
    status_pengelolaan = fields.FileField(upload_to=PathAndRename("serah_terima/dokumen/status_pengelolaan/"),blank=True, null=True)
    pola_pengelolaan = fields.FileField(upload_to=PathAndRename("serah_terima/dokumen/pola_pengelolaan/"),blank=True, null=True)
    regulasi_pemanfaatan_psu = fields.FileField(upload_to=PathAndRename("serah_terima/dokumen/regulasi_pemanfaatan_psu/"),blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table= "kelola_serahterima"

src/e_psu/admin_kelola/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput
from django.core.validators import MinLengthValidator

from .models import AdminKelola
    
class AdminKelolaRegistrationForm(forms.ModelForm):    
    class Meta:
        model = AdminKelola
        fields = ['nama']

src/e_psu/serah_terima/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput

from .models import Dokumen

class DokumenClearableFileInput(ClearableFileInput):
    initial_text = 'Saat ini'
    input_text = 'Ubah'
    clear_checkbox_label = 'hapus'

class DokumenForm(forms.ModelForm):
    class Media:
        js = ['js/serah_terima.js']

    class Meta:
        model = Dokumen
        exclude = ['admin_kelola',]

    video = forms.FileField(widget=DokumenClearableFileInput(attrs={'accept': 'video/*'}))
    foto = forms.ImageField(widget=DokumenClearableFileInput(attrs={'accept': 'image/*'}))
    salinan_laporan = forms.FileField(widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    status_pengelolaan_text = forms.CharField(required=False,label="Status Pengelolaan", max_length=100)
    pola_pengelolaan_text = forms.CharField(required=False,label="Pola Pengelolaan", max_length=100)
    regulasi_pemanfaatan_psu_text = forms.CharField(required=False,label="Regulasi Pemanfaatan PSU", max_length=100)
    status_pengelolaan = forms.FileField(required=False,widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    pola_pengelolaan = forms.FileField(required=False,widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))
    regulasi_pemanfaatan_psu = forms.FileField(required=False,widget=DokumenClearableFileInput(attrs={'accept': 'application/pdf'}))

    def clean(self):
        super().clean()
        status_pengelolaan_text = self.cleaned_data.get('status_pengelolaan_text', None)
        status_pengelolaan = self.cleaned_data.get('status_pengelolaan', None)
        if not status_pengelolaan_text and not status_pengelolaan:
            self.add_error('status_pengelolaan', 'Status Pengelolaan diperlukan')
        
        pola_pengelolaan_text = self.cleaned_data.get('pola_pengelolaan_text', None)
        pola_pengelolaan = self.cleaned_data.get('pola_pengelolaan', None)
        if not pola_pengelolaan_text and not pola_pengelolaan:
            self.add_error('pola_pengelolaan', 'Pola Pengelolaan diperlukan')

        regulasi_pemanfaatan_psu_text = self.cleaned_data.get('regulasi_pemanfaatan_psu_text', None)
        regulasi_pemanfaatan_psu = self.cleaned_data.get('regulasi_pemanfaatan_psu', None)
        if not regulasi_pemanfaatan_psu_text and not regulasi_pemanfaatan_psu:
            self.add_error('regulasi_pemanfaatan_psu', 'Regulasi Pemanfaatan PSU diperlukan')

        return self.cleaned_data

src/e_psu/admin_kelola/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from .forms import AdminKelolaRegistrationForm
from perwakilan_penghuni.forms import PerwakilanPenghuniForm
from account.forms import RegisterForm, LoginForm
from django.db import transaction
from perwakilan_penghuni.models import PerwakilanPenghuni
from serah_terima.models import Dokumen
from laporan.models import BerkasLaporan
from serah_terima.forms import DokumenForm
from laporan.forms import BerkasLaporanForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from account.decorators import admin_kelola_required, anonymous_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def index(request):    
    page = request.GET.get('page', 1)

    dokumen_list = Dokumen.objects.select_related()
    paginator = Paginator(dokumen_list, 10)
    try:
        dokumens = paginator.page(page)
    except PageNotAnInteger:
        dokumens = paginator.page(1)
    except EmptyPage:
        dokumens = paginator.page(paginator.num_pages)
    
    semua_laporan = BerkasLaporan.objects.all()  
    paginator_laporan = Paginator(semua_laporan, 10)
    try:
        laporans = paginator_laporan.page(page)
    except PageNotAnInteger:
        laporans = paginator_laporan.page(1)
    except EmptyPage:
        laporans = paginator_laporan.page(paginator_laporan.num_pages)

    semua_perwakilan_penghuni = PerwakilanPenghuni.objects.all()  
    paginator_penghuni = Paginator(semua_perwakilan_penghuni, 10)
    try:
        perwakilan_penghunis = paginator_penghuni.page(page)
    except PageNotAnInteger:
        perwakilan_penghunis = paginator_penghuni.page(1)
    except EmptyPage:
        perwakilan_penghunis = paginator_penghuni.page(paginator_penghuni.num_pages)

    return render(request, "admin_kelola/index.html", {
        'dokumens' : dokumens,
        'laporans': laporans,
        'perwakilan_penghunis': perwakilan_penghunis
    })

@transaction.atomic
def register_admin_kelola(request):
    account = RegisterForm(request.POST or None, prefix='account')
    admin_kelola = AdminKelolaRegistrationForm(request.POST or None, prefix='admin_kelola')
    context = {
        "admin_kelola_form" : admin_kelola,
        "account_form" : account
    }
    if account.is_valid() and admin_kelola.is_valid():
        user = account.save(commit=False)
        user.user_type = 1
        user.save()
        admin_kelola_data = admin_kelola.save(commit=False)
        admin_kelola_data.user = user
        admin_kelola_data.save()
        return redirect('admin_kelola:login')
    return render(request, 'admin_kelola/auth/register.html', context)

@anonymous_required
def login_admin_kelola(request):
    account = LoginForm(data=request.POST or None, request=request, prefix='admin')
    context = {
        "form" : account
    }
    if account.is_valid():
        return redirect('admin_kelola:index')
    return render(request, 'admin_kelola/auth/login.html', context)

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def logout_admin_kelola(request):
    logout(request)
    return redirect('home')

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def perwakilan_penghuni_tambah(request):    
    account = RegisterForm(request.POST or None, prefix='account')
    perwakilan_penghuni = PerwakilanPenghuniForm(request.POST or None, prefix='perwakilan_penghuni')
    context = {
        "perwakilan_penghuni_form" : perwakilan_penghuni,
        "account_form" : account
    }
    if account.is_valid() and perwakilan_penghuni.is_valid():
        user = account.save(commit=False)
        user.user_type = 2
        user.save()
        perwakilan_penghuni_data = perwakilan_penghuni.save(commit=False)
        perwakilan_penghuni_data.user = user
        perwakilan_penghuni_data.save()
        return redirect('admin_kelola:index')
    return render(request, 'admin_kelola/perwakilan_penghuni/tambah.html', context)


# SERAH TERIMA
@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_tambah(request):    
    if request.method == 'POST':
        form = DokumenForm(request.POST, request.FILES)
        if form.is_valid():
            admin = AdminKelola.objects.get(pk=request.user.id)
            form_serah_terima = form.save(commit=False)
            form_serah_terima.admin_kelola = admin
            form_serah_terima.save()
            nama_psu = form.cleaned_data.get('nama_psu')
            messages.success(request, f'Dokumen berhasil ditambahkan.', extra_tags='serah_terima')
            return redirect('admin_kelola:index')
    else:
        form = DokumenForm()
    return render(request, "admin_kelola/serah_terima/tambah.html", {
        'form' : form
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_tampil(request, id):
    dokumen = Dokumen.objects.get(id=id)
    return render(request, "admin_kelola/serah_terima/tampil.html", {
        'dokumen' : dokumen
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_ubah(request, id):
    try:
        dokumen = Dokumen.objects.get(id = id)
    except Dokumen.DoesNotExist:
        return redirect('admin_kelola:index')
    
    form = DokumenForm(request.POST or None, request.FILES or None, instance = dokumen)

    if form.is_valid():
        admin = AdminKelola.objects.get(pk=request.user.id)
        form_serah_terima = form.save(commit=False)
        form_serah_terima.admin_kelola = admin
        form_serah_terima.save()
        messages.success(request, f'Dokumen berhasil diperbarui.', extra_tags='serah_terima')
        return redirect('admin_kelola:index')

    print(form.errors)
    return render(request, "admin_kelola/serah_terima/ubah.html", {
        'form' : form, 'dokumen' : dokumen
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def serah_terima_hapus(request, id):
    try:
        dokumen = Dokumen.objects.get(id=id)
    except Dokumen.DoesNotExist:
        return redirect('admin_kelola:index')

    dokumen.delete()
    messages.success(request, f'Dokumen berhasil dihapus.', extra_tags='serah_terima')
    return redirect('admin_kelola:index')

# LAPORAN
@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_tambah(request):
    if request.method == 'POST':
        form = BerkasLaporanForm(request.POST, request.FILES)
        if form.is_valid():
            form_laporan = form.save(commit=False)
            form_laporan.status_laporan = 'BELUM'
            form_laporan.user_created = request.user
            form_laporan.save()
            nama_psu_laporan = form.cleaned_data.get('nama_psu_laporan')
            messages.success(request, f'Laporan {nama_psu_laporan} berhasil ditambahkan.', extra_tags='laporan')
            return redirect('admin_kelola:index')
    else:
        form = BerkasLaporanForm()

    return render(request, "admin_kelola/laporan/tambah.html", {
        'form': form
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_tampil(request, id):
    laporan = BerkasLaporan.objects.get(id=id)
    return render(request, "admin_kelola/laporan/tampil.html", {
        'laporan': laporan
    })
    

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_ubah(request, id):
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_kelola:index')
    
    form = BerkasLaporanForm(request.POST or None, request.FILES or None, instance = laporan)

    if form.is_valid():
        form.save()
        nama_psu = form.cleaned_data.get('nama_psu_laporan')
        messages.success(request, f'Laporan {nama_psu} berhasil diperbarui.', extra_tags='laporan')
        return redirect('admin_kelola:index')

    return render(request, 'admin_kelola/laporan/ubah.html', {
        'form': form
    })

@login_required(login_url='/admin_kelola/login')
@admin_kelola_required
def laporan_hapus(request, id):
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_kelola:index')
    laporan.delete()
    messages.success(request, f'Laporan {laporan.nama_psu_laporan} berhasil dihapus.', extra_tags='laporan')
    return redirect('admin_kelola:index')

src/e_psu/admin_kelola/templates/admin_kelola/serah_terima/cari.html
{% extends 'header.html' %}
{% load static %}

<!-- Masthead -->
{% block content %}
    <div class="container py-5">
        <div class="card">
            <div class="card-header text-center">
                <h2>Hasil Pencarian Dokumen dengan Nama '{{ request.GET.psu }}'</h2>
            </div>
            <div class="card-body">
                {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
                <div class="mb-4">
                    <a href="{% url 'serah_terima:tambah' %}" class="btn btn-success d-inline">Tambah</a>
                    <form class="form-inline d-inline float-right" action="{% url 'serah_terima:cari' %}" method="get">
                        <input name="psu" class="form-control" type="text" placeholder="Cari Dokumen" value="{{ request.GET.psu }}">
                        <button type="submit" class="btn btn-primary">Cari</button>
                    </form>
                </div>                
                <table class="mt-2 table">
                    <thead class="thead-light">
                        <tr>
                            <th shape="col">PSU</th>
                            <th shape="col">Perumahan</th>
                            <th shape="col">Video</th>
                            <th shape="col">Foto</th>
                            <th shape="col">Salinan Laporan</th>
                            <th shape="col">Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dokumen in dokumens %}
                            <tr>
                                <td>{{ dokumen.nama_psu }}</td>
                                <td>{{ dokumen.perumahan }}</td>
                                <td>
                                    <a href="{{ dokumen.video.url }}" class="btn btn-secondary" target="_blank">Unduh Video</a>                                    
                                </td>
                                <td>
                                    <a href="{{ dokumen.foto.url }}" class="btn btn-secondary" target="_blank">Unduh Foto</a>
                                </td>
                                <td>
                                    <a href="{{ dokumen.salinan_laporan.url }}" class="btn btn-secondary" target="_blank">Unduh Salinan</a>                                    
                                </td>
                                <td>
                                    <a href="{% url 'serah_terima:tampil' id=dokumen.id %}" type="button" class="btn btn-primary">Lihat</a>
                                    <a href="{% url 'serah_terima:ubah' id=dokumen.id %}" type="button" class="btn btn-warning">Ubah</a>
                                    <a href="{% url 'serah_terima:hapus' id=dokumen.id %}" type="button" class="btn btn-danger" 
                                        onclick="return confirm('Apakah Anda yakin untuk menghapus dokumen {{ dokumen.nama_psu }}?')">
                                        Hapus
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% if dokumens.has_other_pages %}
                    <ul class="pagination">
                        {% if dokumens.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ dokumens.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">&laquo;</span>
                        </li>
                        {% endif %}
                        {% for i in dokumens.paginator.page_range %}
                            {% if dokumens.number == i %}
                                <li class="page-item active">
                                    <span class="page-link">{{ i }} 
                                        <span class="sr-only">(current)</span>
                                    </span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if dokumens.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ dokumens.next_page_number }}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
            <div class="card-footer">
                <a href="{% url 'serah_terima:index' %}" type="button" class="btn btn-success">Kembali</a>
            </div>
        </div>
    </div>
{% endblock %}

src/e_psu/admin_kelola/templates/admin_kelola/serah_terima/ubah.html
{% extends 'header.html' %}
{% load static %}

{% load crispy_forms_tags %}

<!-- Masthead -->
{% block content %}
    <div class="container py-5">
        <div class="card">
            <div class="card-header text-center">
                <h2>Ubah Serah Terima {{ dokumen.id }}</h2>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="div_id_video" class="form-group mb-4"> 
                        <label for="id_video" class=" requiredField">
                            Video<span class="asteriskField">*</span> 
                        </label> 
                        <div>
                            Saat ini: 
                            <video width="100%" controls>
                                <source src="{{ form.video.value.url }}" type="video/mp4">
                            </video>
                            Ubah: <br>
                            <input type="file" name="video" accept="video/*" class="dokumenclearablefileinput form-control-file" id="id_video"> 
                        </div> 
                    </div> 
                    <div id="div_id_foto" class="form-group mb-4"> 
                        <label for="id_foto" class=" requiredField">
                            Foto<span class="asteriskField">*</span> 
                        </label> 
                        <div>
                            Saat ini: <br>
                            <div class="text-center">
                                <img style="max-width: 100%" src="{{ form.foto.value.url }}" alt="Foto {{ form.nama_psu.value }}">
                            </div>
                            Ubah: <br>
                            <input type="file" name="foto" accept="image/*" class="dokumenclearablefileinput form-control-file" id="id_foto"> 
                        </div> 
                    </div>
                    <div id="div_id_salinan_laporan" class="form-group mb-4"> 
                        <label for="id_salinan_laporan" class=" requiredField">
                            Salinan laporan<span class="asteriskField">*</span> 
                        </label> 
                        <div>
                            Saat ini: <br>
                            <a href="{{ form.salinan_laporan.value.url }}" class="btn btn-primary" download>Unduh Salinan Laporan</a> <br>
                            Ubah: <br>
                            <input type="file" name="salinan_laporan" accept="application/pdf" class="dokumenclearablefileinput form-control-file" id="id_salinan_laporan"> 
                        </div> 
                    </div>
                    <div class="form-group mb-4">
                        <div class="label">Status Pengelolaan* (pilih minimal satu)</div>
                        {% if form.errors.status_pengelolaan %}
                            <small class="text-danger">
                                <strong>Status Pengelolaan diperlukan</strong>
                            </small>
                        {% endif %}
                        <div>
                            <label style="font-size: 16px;">Teks</label>
                            <div class="input-group mb-3">
                                <input class="textinput textInput form-control" id="id_status_pengelolaan_text" name="status_pengelolaan_text" type="text" placeholder="Status Pengelolaan" maxlength="100" value="{{ dokumen.status_pengelolaan_text }}">
                            </div>
                            <label style="font-size: 16px;">File</label>
                            <div>
                                {% if dokumen.status_pengelolaan %}
                                Saat ini: <br>
                                <a href="{{ dokumen.status_pengelolaan.url }}" class="btn btn-primary" download>Unduh Status Pengelolaan</a> 
                                <input type="checkbox" name="status_pengelolaan-clear" id="status_pengelolaan-clear_id">
                                <label for="status_pengelolaan-clear_id">hapus</label><br>
                                Ubah: <br>
                                {% endif %}
                                <input type="file" name="status_pengelolaan" accept="application/pdf" class="dokumenclearablefileinput form-control-file" id="id_status_pengelolaan"> 
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <div class="label">Pola Pengelolaan* (pilih minimal satu)</div>
                        {% if form.errors.pola_pengelolaan %}
                            <small class="text-danger">
                                <strong>Pola Pengelolaan diperlukan</strong>
                            </small>
                        {% endif %}
                        <div>
                            <label style="font-size: 16px;">Teks</label>
                            <div class="input-group mb-3">
                                <input class="textinput textInput form-control" id="id_pola_pengelolaan_text" name="pola_pengelolaan_text" type="text" placeholder="Pola Pengelolaan" maxlength="100" value="{{ dokumen.pola_pengelolaan_text }}">
                            </div>
                            <label style="font-size: 16px;">File</label>
                            <div>
                                {% if dokumen.pola_pengelolaan %}
                                Saat ini: <br>
                                <a href="{{ dokumen.pola_pengelolaan.url }}" class="btn btn-primary" download>Unduh Pola Pengelolaan</a>
                                <input type="checkbox" name="pola_pengelolaan-clear" id="pola_pengelolaan-clear_id">
                                <label for="pola_pengelolaan-clear_id">hapus</label><br>
                                Ubah: <br>
                                {% endif %}
                                <input type="file" name="pola_pengelolaan" accept="application/pdf" class="dokumenclearablefileinput form-control-file" id="id_pola_pengelolaan"> 
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <div class="label">Regulasi Pemanfaatan PSU* (pilih minimal satu)</div>
                        {% if form.errors.regulasi_pemanfaatan_psu %}
                            <small class="text-danger">
                                <strong>Regulasi Pemanfaatan PSU diperlukan</strong>
                            </small>
                        {% endif %}
                        <div>
                            <label style="font-size: 16px;">Teks</label>
                            <div class="input-group mb-3">
                                <input class="textinput textInput form-control" id="id_regulasi_pemanfaatan_psu_text" name="regulasi_pemanfaatan_psu_text" type="text" placeholder="Regulasi Pemanfaatan PSU" maxlength="100" value="{{ dokumen.regulasi_pemanfaatan_psu_text }}">
                            </div>
                            <label style="font-size: 16px;">File</label>
                            <div>
                                {% if dokumen.regulasi_pemanfaatan_psu %}
                                Saat ini: <br>
                                <a href="#" class="btn btn-primary" download>Unduh Regulasi Pemanfaatan PSU</a>
                                <input type="checkbox" name="regulasi_pemanfaatan_psu-clear" id="regulasi_pemanfaatan_psu-clear_id">
                                <label for="regulasi_pemanfaatan_psu-clear_id">hapus</label><br>
                                Ubah: <br>
                                {% endif %}
                                <input type="file" name="regulasi_pemanfaatan_psu" accept="application/pdf" class="dokumenclearablefileinput form-control-file" id="id_regulasi_pemanfaatan_psu"> 
                            </div>
                        </div>
                    </div>
                    <hr class="my-3">
                    <a href="{% url 'admin_kelola:index' %}" type="button" class="btn btn-danger">Batal</a>
                    <button type="submit" class="btn btn-success">Simpan</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}