src/e_psu/admin_kelola/urls.py
from django.urls import path

from . import views

app_name = "admin_kelola"
urlpatterns = [
    path("login", views.login_admin_kelola, name="login"),
    path("register", views.register_admin_kelola, name="register"),
    path("logout", views.logout_admin_kelola, name="logout"),
    path("dashboard", views.index, name="index"),
    path("perwakilan_penghuni/tambah", views.perwakilan_penghuni_tambah, name="perwakilan_penghuni_tambah"),
    path("laporan/tambah", views.laporan_tambah, name="laporan_tambah"),
    path("laporan/tampil/<int:id>", views.laporan_tampil, name="laporan_tampil"),
    path("laporan/ubah/<int:id>", views.laporan_ubah, name="laporan_ubah"),
    path("laporan/hapus/<int:id>", views.laporan_hapus, name="laporan_hapus"),
    path("serah_terima/tambah", views.serah_terima_tambah, name="serah_terima_tambah"),
    path("serah_terima/tampil/<int:id>", views.serah_terima_tampil, name="serah_terima_tampil"),
    path("serah_terima/ubah/<int:id>", views.serah_terima_ubah, name="serah_terima_ubah"),
    path("serah_terima/hapus/<int:id>", views.serah_terima_hapus, name="serah_terima_hapus"),
]

src/e_psu/admin_skpd/urls.py
from django.urls import path

from . import views

app_name = "admin_skpd"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("register", views.register_view, name="register"),
    path('dashboard', views.index_view, name="index"),
    path('logout', views.logout_view, name="logout"),
    path('profile', views.display_profile_view, name="display_profile"),
    path('profile/edit', views.change_profile_view, name="change_profile"),
    path("laporan/<int:id>", views.detail_laporan_view, name="detail_laporan"),
    path("laporan/edit/<int:id>", views.update_laporan_view, name="update_laporan"),
]

src/e_psu/e_psu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path("", home_view, name="home"),
    path('admin/', admin.site.urls),
    path('admin_kelola/serah_terima/', include("serah_terima.urls")),
    path('laporan/', include("laporan.urls")),
    path('warga/', include("warga.urls")),
    path('admin_kelola/', include("admin_kelola.urls")),
    path('admin_skpd/', include("admin_skpd.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/e_psu/warga/urls.py
from django.urls import path

from . import views

app_name = "warga"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("dashboard", views.index_view, name="index"),
    path("laporan/<int:id>", views.detail_laporan_view, name="detail_laporan"),
    path("laporan", views.add_laporan_view, name="add_laporan"),
    path("profile", views.display_profile_view, name="display_profile"),
    path("profile/edit", views.change_profile_view, name="change_profile"),
]

src/e_psu/templates/footer.html
<footer class="page-footer font-small pt-4" style="background-color: #03a678;">
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3">
                <!-- Footer Content -->
                <h5 class="text-uppercase text-white">Footer Content</h5>
                <p class="text-white">Here you can use rows and columns to organize your footer content.</p>
            </div>

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-2 mb-md-0 mb-3">
                <!-- Links -->
                <h5 class="text-uppercase text-white">Pelaporan</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!" class="text-white">Link 1</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 2</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 3</a>
                    </li>
                </ul>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-md-0 mb-3">
                <!-- Links -->
                <h5 class="text-uppercase text-white">Pemantauan</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!" class="text-white">Link 1</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 2</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 3</a>
                    </li>
                </ul>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-md-0 mb-3">
                <!-- Links -->
                <h5 class="text-uppercase text-white">Pengelolaan</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!" class="text-white">Link 1</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 2</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 3</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-white" style="background-color: #025b42">
        © 2020 Copyright:<a href="https://mdbootstrap.com/" class="text-white"> Kabupaten Sidoarjo</a>
    </div>
</footer>

src/e_psu/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>E-Pantau PERUMAHAN KABUPATEN SIDOARJO</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.3.1/dist/sweetalert2.all.min.js"></script>
</body>

</html>

src/e_psu/templates/home.html
{% extends 'header.html' %}
{% load static %}

<!-- Masthead -->
{% block content %}
<header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
    <div class="row">
        <div class="col-xl-9 mx-auto">
        <h1 class="mb-5">Build a landing page for your business or project and generate more leads!</h1>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
        <form>
            <div class="form-row">
            <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
            </div>
            <div class="col-12 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
            </div>
            </div>
        </form>
        </div>
    </div>
    </div>
</header>

<!-- Icons Grid -->
<section class="features-icons bg-light text-center">
    <div class="container">
    <div class="row">
        <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
            <i class="icon-screen-desktop m-auto text-primary"></i>
            </div>
            <h3>Fully Responsive</h3>
            <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
        </div>
        </div>
        <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
            <i class="icon-layers m-auto text-primary"></i>
            </div>
            <h3>Bootstrap 4 Ready</h3>
            <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
        </div>
        </div>
        <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
            <i class="icon-check m-auto text-primary"></i>
            </div>
            <h3>Easy to Use</h3>
            <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
        </div>
        </div>
    </div>
    </div>
</section>

<!-- Image Showcases -->
<section class="showcase">
    <div class="container-fluid p-0">
    <div class="row no-gutters">

        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'img/bg-showcase-1.jpg' %}');"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h2>Fully Responsive Design</h2>
        <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-lg-6 text-white showcase-img" style="background-image: url('{% static 'img/bg-showcase-2.jpg' %}');"></div>
        <div class="col-lg-6 my-auto showcase-text">
        <h2>Updated For Bootstrap 4</h2>
        <p class="lead mb-0">Newly improved, and full of great utility classes, Bootstrap 4 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 4!</p>
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'img/bg-showcase-3.jpg' %}');"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h2>Easy to Use &amp; Customize</h2>
        <p class="lead mb-0">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>
        </div>
    </div>
    </div>
</section>

<!-- Testimonials -->
<section class="testimonials text-center bg-light">
    <div class="container">
    <h2 class="mb-5">What people are saying...</h2>
    <div class="row">
        <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{% static 'img/testimonials-1.jpg' %}" alt="">
            <h5>Margaret E.</h5>
            <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
        </div>
        </div>
        <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{% static 'img/testimonials-2.jpg' %}" alt="">
            <h5>Fred S.</h5>
            <p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>
        </div>
        </div>
        <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{% static 'img/testimonials-3.jpg' %}" alt="">
            <h5>Sarah W.</h5>
            <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
        </div>
        </div>
    </div>
    </div>
</section>

<!-- Call to Action -->
<section class="call-to-action text-white text-center">
    <div class="overlay"></div>
    <div class="container">
    <div class="row">
        <div class="col-xl-9 mx-auto">
        <h2 class="mb-4">Ready to get started? Sign up now!</h2>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
        <form>
            <div class="form-row">
            <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
            </div>
            <div class="col-12 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
            </div>
            </div>
        </form>
        </div>
    </div>
    </div>
</section>
{% endblock content %}

src/e_psu/templates/navbar.html
<nav class="navbar navbar-light" style="background-color: #03a678;">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="http://4.bp.blogspot.com/-FtOrR7FqtEg/Tdufk5MUD9I/AAAAAAAADrE/1FMbaYHMrR8/s320/Kabupaten_Sidoarjo.png" class="m-2" alt="logo_sidoarjo" width="75" height="75">
    </a>
    <span class="text-white" style="font-size: x-large;">E-Pantau PERUMAHAN KABUPATEN SIDOARJO</span> 
</nav>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #025b42;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link text-white" href="/">Beranda <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pelaporan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Ajukan Laporan</a>
                    <a class="dropdown-item" href="#">Cek Status</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pemantauan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pengelolaan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Sosialisasi Serah Terima</a>
                    <a class="dropdown-item" href="#">Laporan Masyarakat</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!-- Belum Login -->
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link text-white dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{user.username}} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% if user.user_type == 1 %}
                            <a class="dropdown-item" href="#">Ganti profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'admin_kelola:logout' %}">Logout</a>
                        {% endif %}
                        {% if user.user_type == 3 %}
                            <a class="dropdown-item" href="{% url 'admin_skpd:display_profile' %}">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'admin_skpd:logout' %}">Logout</a>
                        {% endif %}
                        {% if user.user_type == 4 %}
                            <a class="dropdown-item" href="{% url 'warga:display_profile' %}">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'warga:logout' %}">Logout</a>
                        {% endif %}
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'warga:login' %}">Login</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'warga:register' %}">Register</a>
                </li>
            {% endif %}

            <!-- Sudah Login -->            
        </ul>
    </div>
</nav>