src/e_psu/admin_skpd/urls.py
from django.urls import path

from . import views

app_name = "admin_skpd"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("register", views.register_view, name="register"),
    path('dashboard', views.index_view, name="index"),
    path('logout', views.logout_view, name="logout"),
    path('profile', views.display_profile_view, name="display_profile"),
    path('profile/edit', views.change_profile_view, name="change_profile"),
    path("laporan/<int:id>", views.detail_laporan_view, name="detail_laporan"),
    path("laporan/edit/<int:id>", views.update_laporan_view, name="update_laporan"),
]

src/e_psu/e_psu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path("", home_view, name="home"),
    path('admin/', admin.site.urls),
    path('admin_kelola/serah_terima/', include("serah_terima.urls")),
    path('laporan/', include("laporan.urls")),
    path('warga/', include("warga.urls")),
    path('admin_kelola/', include("admin_kelola.urls")),
    path('admin_skpd/', include("admin_skpd.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/e_psu/admin_skpd/models.py
from django.db import models
from account.models import Account
from django.db.models.signals import post_save
# Create your models here.
class AdminSKPD(models.Model):
    user = models.OneToOneField(Account,on_delete=models.CASCADE, primary_key = True)
    nama = models.CharField(max_length=30)

    class Meta:
        db_table= "kelola_adminskpd"
    
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            profile, created = AdminSKPD.objects.get_or_create(user=instance)
    
    post_save.connect(create_user_profile, sender=Account)

src/e_psu/admin_skpd/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput
from django.core.validators import MinLengthValidator

from .models import AdminSKPD
    
class AdminSKPDRegistrationForm(forms.ModelForm):    
    class Meta:
        model = AdminSKPD
        fields = ['nama']

src/e_psu/admin_skpd/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AdminSKPDRegistrationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from account.forms import RegisterForm, LoginForm, EditAccountForm
from account.decorators import admin_skpd_required, anonymous_required
from django.db import transaction
from laporan.models import BerkasLaporan
from laporan.forms import UpdateStatusForm, UpdatePenangananForm
from .models import AdminSKPD
# Create your views here.

@login_required(login_url='/admin_skpd/login')
@admin_skpd_required
def index_view(request):    
    page = request.GET.get('page', 1)

    semua_laporan = BerkasLaporan.objects.all()  
    paginator_laporan = Paginator(semua_laporan, 10)
    try:
        laporans = paginator_laporan.page(page)
    except PageNotAnInteger:
        laporans = paginator_laporan.page(1)
    except EmptyPage:
        laporans = paginator_laporan.page(paginator_laporan.num_pages)

    return render(request, "admin_skpd/index.html", {
        'laporans': laporans,
    })

@transaction.atomic
def register_view(request):
    account = RegisterForm(request.POST or None, prefix='account')
    admin_skpd = AdminSKPDRegistrationForm(request.POST or None, prefix='admin_skpd')
    context = {
        "admin_skpd_form" : admin_skpd,
        "account_form" : account
    }
    if account.is_valid() and admin_skpd.is_valid():
        user = account.save(commit=False)
        user.user_type = 3
        user.save()
        admin_skpd_data = admin_skpd.save(commit=False)
        admin_skpd_data.user = user
        admin_skpd_data.save()
        return redirect('admin_skpd:login')
    return render(request, 'admin_skpd/auth/register.html', context)

@anonymous_required
def login_view(request):
    account = LoginForm(data=request.POST or None, request=request, prefix='skpd')
    context = {
        "form" : account
    }
    if account.is_valid():
        return redirect('admin_skpd:index')
    return render(request, 'admin_skpd/auth/login.html', context)

@login_required(login_url='/admin_skpd/login')
@admin_skpd_required
def logout_view(request):
    logout(request)
    return redirect('home')

@login_required(login_url='/admin_skpd/login')
@admin_skpd_required
def display_profile_view(request):
    admin_skpd = AdminSKPD.objects.get(pk=request.user.id)
    context = {
        "admin_skpd" : admin_skpd
    }
    return render(request, 'admin_skpd/auth/display_profile.html', context)

@login_required(login_url='/admin_skpd/login')
@admin_skpd_required
def change_profile_view(request):
    admin_skpd = AdminSKPD.objects.get(pk=request.user.id)
    account = EditAccountForm(request.POST or None, prefix='account', instance= request.user)
    admin_skpd_form = AdminSKPDRegistrationForm(request.POST or None, prefix='admin_skpd',instance = admin_skpd)
    if admin_skpd_form.is_valid() and account.is_valid():
        admin_skpd_form.save()
        account.save()
        messages.success(request, f'Profile berhasil diperbarui.')
        return redirect('admin_skpd:display_profile')
    context = {
        "admin_skpd_form" : admin_skpd_form,
        "account" : account,
    }
    return render(request, 'admin_skpd/auth/change_profile.html', context)

@login_required(login_url='/admin_skpd/login')
@admin_skpd_required
def detail_laporan_view(request, id):
    try:
        laporan = BerkasLaporan.objects.get(id=id)
    except BerkasLaporan.DoesNotExist:
        return redirect('admin_skpd:index')

    return render(request, "admin_skpd/laporan/detail_laporan.html", {
        'laporan': laporan
    })

@login_required(login_url='/admin_skpd/login')
@admin_skpd_required
def update_laporan_view(request, id):
    try:
        berkas_laporan = BerkasLaporan.objects.get(id=id)
    except:
        return redirect('admin_skpd:index')

    update_status_form = UpdateStatusForm(request.POST or None, instance=berkas_laporan)
    update_penanganan_form = UpdatePenangananForm(request.POST or None, instance=berkas_laporan)

    if update_status_form.is_valid():
        admin_skpd = AdminSKPD.objects.get(pk=request.user.id)
        berkas_laporan = update_status_form.save(commit=False)
        berkas_laporan.admin_status_laporan = admin_skpd
        berkas_laporan.save()
        messages.success(request, f'Laporan {id} berhasil diperbaharui', extra_tags='laporan')
        return redirect('admin_skpd:index')    
    elif update_penanganan_form.is_valid():        
        admin_skpd = AdminSKPD.objects.get(pk=request.user.id)
        berkas_laporan = update_penanganan_form.save(commit=False)
        berkas_laporan.admin_penanganan_laporan = admin_skpd
        berkas_laporan.save()
        messages.success(request, f'Laporan {id} berhasil diperbaharui', extra_tags='laporan')
        return redirect('admin_skpd:index')

    return render(request, "admin_skpd/laporan/update_laporan.html", {
        'update_status_form': update_status_form,
        'update_penanganan_form': update_penanganan_form,
    })

src/e_psu/admin_skpd/templates/admin_skpd/index.html
{% extends "header.html" %}
{% load static %}

{% block content %}
    <div class="container py-5">
        <div class="card">
            <div class="card-header text-center">
                <h2>Laporan Masyarakat</h2>
            </div>
            <div class="card-body">
                {% for message in messages %}
                    {% if message.extra_tags == 'laporan' %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
                <table class="mt-2 table">
                    <thead class="thead-light">
                        <tr>
                            <th shape="col">Tanggal Entri</th>
                            <th shape="col">ID</th>
                            <th shape="col">Status Laporan</th>
                            <th shape="col">Nama PSU</th>
                            <th shape="col">Judul Laporan</th>
                            <th shape="col">Bukti Foto</th>
                            <!-- <th shape="col">Bukti Video</th> -->
                            <th shape="col">Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for laporan in laporans %}
                            <tr>
                                <td>{{ laporan.tanggal_entri_laporan }}</td>
                                <td>{{ laporan.id }}</td>
                                <td>
                                    {% if laporan.status_laporan == 'BELUM' %}
                                        <span style="background-color: #f34d30;width: max-content;padding: 10px;border-radius:4px;color:white">
                                            Belum Diproses
                                        </span>
                                    {% endif %}
                                    {% if laporan.status_laporan == 'SEDANG' %}
                                        <span style="background-color: #fbff24;width: max-content;padding: 10px;border-radius:4px;color:white">
                                            Sedang Diproses
                                        </span>
                                    {% endif %}
                                    {% if laporan.status_laporan == 'SUDAH' %}
                                        <span style="background-color: #03a678;width: max-content;padding: 10px;border-radius:4px;color:white">
                                            Telah Diproses
                                        </span>
                                    {% endif %}
                                </td>
                                <td>{{ laporan.nama_psu_laporan }}</td>
                                <td>{{ laporan.judul_laporan }}</td>
                                <td>
                                    <a href="{{ laporan.foto_laporan.url }}" class="btn btn-secondary" target="_blank">Unduh Bukti Foto</a>
                                </td>
                                <!-- <td>
                                    <a href="{{ laporan.video.url }}" class="btn btn-secondary" target="_blank">Unduh Bukti Video</a>                                    
                                </td> -->
                                <td>
                                    <a href="{% url 'admin_skpd:detail_laporan' id=laporan.id %}" type="button" class="btn btn-info">Lihat Laporan</a>
                                    <a href="{% url 'admin_skpd:update_laporan' id=laporan.id %}" type="button" class="btn btn-warning">Update Laporan</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% if laporans.has_other_pages %}
                <ul class="pagination">
                    {% if laporans.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ laporans.previous_page_number }}" class="page-link"> &laquo;</a>
                    </li>

                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link"> &laquo; </span>
                    </li>
                    {% endif %}

                    {% for i in laporans.paginator.page_range %}
                        {% if laporans.number == i %}
                            <li class="page-item active">
                                <span class="page-link">
                                    {{ i }}
                                    <span class="sr-only">(current)</span>
                                </span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="?page={{ i }}" class="page-link"> {{ i }} </a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if laporans.has_next %}
                        <li class="page-item">
                            <a href="?page={{ laporans.next_page_number }}" class="page-link"> &raquo; </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link"> &raquo; </span>
                        </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>        
    </div>
{% endblock %}